#!/usr/bin/env python3
"""Generate the Ultra variants of Sunstone's heavier effects and refresh shared shader copies.

mod/postfx/hdr_u and mod/postfx/ssao_u are copies of hdr and ssao with every reduced-resolution pass at half its
scale (and AO_SCALE halved to match), for a scene rendered at twice the window size. Every pass gets the
SCALE_HALVED define, so the shaders can keep their radii and bloom levels the same on screen.

#include cannot leave an effect folder, so the GLSL that lite shares with hdr is copied into lite/.
Stdlib only. Run after changing anything in hdr/ or ssao/.
"""
import re
import shutil
from pathlib import Path

POSTFX = Path(__file__).resolve().parent.parent / "mod" / "postfx"
VARIANTS = {"hdr": "hdr_u", "ssao": "ssao_u"}
SHARED = {"lite": ("hdr", ["colour.glsl", "foliage.glsl", "display.glsl"])}


def fmt(v):
    return f"{v:.8f}".rstrip("0").rstrip(".")


def variant_ini(text):
    out = ["; Generated by tools/make_variants.py from the effect without the _u suffix; do not edit.\n"]
    section = None
    pass_lines = []

    def flush():
        if not pass_lines:
            return
        if not any(re.match(r"defines\s*=", ln) for ln in pass_lines):
            pass_lines.insert(_after_shader(pass_lines), "defines=SCALE_HALVED\n")
        out.extend(pass_lines)
        pass_lines.clear()

    for line in text.splitlines(keepends=True):
        body = line.rstrip("\r\n")
        end = line[len(body):]
        head = re.match(r"\s*\[([^\]]+)\]", body)
        if head:
            flush()
            section = head.group(1).strip().lower()
        if section and section.startswith("pass."):
            m = re.match(r"(\s*scale\s*=\s*)([0-9.]+)\s*$", body)
            if m and float(m.group(2)) < 1.0:
                body = m.group(1) + fmt(float(m.group(2)) / 2.0)
            m = re.match(r"(\s*defines\s*=\s*)(.*)$", body)
            if m:
                defs = []
                for d in m.group(2).split(","):
                    name, eq, value = d.strip().partition("=")
                    if name == "AO_SCALE":
                        value = fmt(float(value) / 2.0)
                    defs.append(name + eq + value)
                body = m.group(1) + ",".join(defs + ["SCALE_HALVED"])
            pass_lines.append(body + end)
        elif section == "effect" and re.match(r"\s*title\s*=", body):
            out.append(body + " (Ultra)" + end)
        else:
            out.append(line)
    flush()
    return "".join(out)


def _after_shader(lines):
    for i, ln in enumerate(lines):
        if re.match(r"\s*shader\s*=", ln):
            return i + 1
    return 1


def make_variant(src, dst):
    if dst.exists():
        shutil.rmtree(dst)
    dst.mkdir()
    for f in sorted(src.iterdir()):
        if f.name == "effect.ini":
            text = f.read_bytes().decode("utf-8")
            (dst / f.name).write_bytes(variant_ini(text).encode("utf-8"))
        elif f.is_file():
            shutil.copyfile(f, dst / f.name)
    print(f"wrote {dst}")


def main():
    for src, dst in VARIANTS.items():
        make_variant(POSTFX / src, POSTFX / dst)
    for dst, (src, names) in SHARED.items():
        for name in names:
            shutil.copyfile(POSTFX / src / name, POSTFX / dst / name)
        print(f"refreshed {', '.join(names)} in {POSTFX / dst}")


if __name__ == "__main__":
    main()
