#!/usr/bin/env python3
"""Kindjal held/melee weapon meshes: shiv (the Prod), gauntlet (the Fire Punch / Hellfist), railspike (No More Nails).

    python meshes_held.py            write tools/meshes/<slug>.gltf/.bin/.png and print the stats
    python meshes_held.py --check    compare the regenerated bytes with the files on disk

Importing this module has no side effects. It exports

    MODELS = [(slug, build_fn, vanilla_reference_name), ...]      build_fn() -> (Mesh, Texture)

and the helpers generate() / write(). Everything is built with make_meshes' Mesh / Texture / glTF writer; the part builders
here are faces-based (a loft of closed rings with flat or ring-smoothed shading), because a blade, a fist and a sledge
are not surfaces of revolution. Same rules as the other meshes: one primitive, one 128x128 texture, u16 indices, Y up
along the weapon, origin where the vanilla asset has it, bounding box agreeing with the vanilla reference (within 12%).

shiv      Prod                 no vanilla mesh   reference size derived from BaseballBat (blade 45% of the bat's length)
gauntlet  Fire Punch           no vanilla mesh   reference size derived from BaseballBat (35% of its length, centred on 0)
railspike No More Nails        TailNail          sledge + rust-orange railway spike through a plank

Original art, nothing from the game. Fixed seeds, stdlib only, deterministic.
"""
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import make_meshes as mm  # noqa: E402
from make_meshes import (Fbm, Mesh, Texture, TAU, TEX, add, clamp, cross, dot, length, lerp, mix, mul, shade, smooth,  # noqa: E402
                         sub, tube, unit, wrapdiff)

OUT = Path(__file__).resolve().parent / "meshes"
TOL = 0.12
TRI_MIN, TRI_MAX = 400, 1800

BAT_LEN = 25.876  # the vanilla BaseballBat is 25.876 long along Y (-12.581 .. 13.295)

# Reference boxes (min, max), (vanilla name, tris). TailNail and BaseballBat are measured (xomtool convert, Bundl09.xom).
# shiv: the real BaseballBat box, every axis (the shiv spans the bat's length and depth and its hand-held handle covers
#       where the bat is gripped). gauntlet: the Fire Punch has no vanilla mesh, so x and z are the bat's and y is the
#       35 percent of the bat's length the brief asks for (a design box, not a vanilla match on y). railspike: TailNail.
REF = {
    "shiv": ("BaseballBat", (-2.887, -12.581, -2.855), (2.887, 13.295, 2.855), 504),
    "gauntlet": ("BaseballBat", (-2.887, -0.175 * BAT_LEN, -2.855), (2.887, 0.175 * BAT_LEN, 2.855), 504),
    "railspike": ("TailNail", (-6.139, -4.168, -9.520), (6.139, 22.109, 8.394), 358),
}


# ---------------------------------------------------------------- face based part builders
def centroid(pts):
    n = len(pts)
    return (sum(p[0] for p in pts) / n, sum(p[1] for p in pts) / n, sum(p[2] for p in pts) / n)


def ring_y(y, cx, cz, rx, rz, n=12, p=2.0):
    """A closed ring in the plane at height y (a superellipse of exponent p), angle 0 at +X, then toward +Z."""
    out = []
    for j in range(n):
        c, s = math.cos(TAU * j / n), math.sin(TAU * j / n)
        out.append((cx + rx * math.copysign(abs(c) ** (2.0 / p), c), y, cz + rz * math.copysign(abs(s) ** (2.0 / p), s)))
    return out


def ring_z(z, cx, cy, rx, ry, n=12, p=2.0):
    """The same for a part whose long axis is Z: a ring at depth z, angle 0 at +X, then toward +Y."""
    out = []
    for j in range(n):
        c, s = math.cos(TAU * j / n), math.sin(TAU * j / n)
        out.append((cx + rx * math.copysign(abs(c) ** (2.0 / p), c), cy + ry * math.copysign(abs(s) ** (2.0 / p), s), z))
    return out


def ring_x(x, cy, cz, ry, rz, n=12, p=2.0):
    """The same for a part whose long axis is X (a thumb): a ring at x, angle 0 at +Y, then toward +Z."""
    out = []
    for j in range(n):
        c, s = math.cos(TAU * j / n), math.sin(TAU * j / n)
        out.append((x, cy + ry * math.copysign(abs(c) ** (2.0 / p), c), cz + rz * math.copysign(abs(s) ** (2.0 / p), s)))
    return out


def loft(mesh, gid, rings, rect=None, uv=None, cap_uv=None, caps=(True, True), flat=False):
    """A closed part from a stack of rings (every ring has the same point count, same circulation). Between two rings
    each edge makes one quad, wound to face away from the rings' centroid line. flat=True gives every quad its own
    smoothing group (crisp facets); otherwise one group per ring gap, so the seam round the ring is smooth. Ring end
    caps are fans (outward along the loft). u runs round the ring and v along the loft inside `rect` (texels), unless
    uv(p, n) -> (u, v) in 0..1 is given (planar maps); cap_uv(p) -> (u, v) 0..1 maps the caps."""
    mesh.begin_part()
    n = len(rings[0])
    cents = [centroid(r) for r in rings]
    cum = [0.0]
    for k in range(1, len(rings)):
        cum.append(cum[-1] + length(sub(cents[k], cents[k - 1])))
    total = cum[-1] or 1.0

    def uv_of(p, nrm, j, c, k):
        if uv:
            return uv(p, nrm)
        x0, y0, x1, y1 = rect
        return ((x0 + (x1 - x0) * (j + c) / n) / TEX, (y0 + (y1 - y0) * cum[k] / total) / TEX)

    for k in range(len(rings) - 1):
        mid = mul(add(cents[k], cents[k + 1]), 0.5)
        for j in range(n):
            j1 = (j + 1) % n
            q = [(rings[k][j], j, 0, k), (rings[k + 1][j], j, 0, k + 1), (rings[k + 1][j1], j, 1, k + 1),
                 (rings[k][j1], j, 1, k)]
            pts = [t[0] for t in q]
            fc = centroid(pts)
            out = sub(fc, mid)
            nrm = unit(cross(sub(pts[1], pts[0]), sub(pts[2], pts[0])))
            if dot(nrm, out) < 0:
                nrm = mul(nrm, -1.0)
            g = (gid, k, j) if flat else (gid, k)
            ids = [mesh.vert(p, uv_of(p, nrm, jj, c, kk), g) for p, jj, c, kk in q]
            mesh.tri_out(ids[0], ids[1], ids[2], out)
            mesh.tri_out(ids[0], ids[2], ids[3], out)
    for end, (k, enabled) in enumerate(((0, caps[0]), (len(rings) - 1, caps[1]))):
        if not enabled:
            continue
        ring = rings[k]
        out = sub(cents[k], cents[1 if k == 0 else k - 1])
        if cap_uv:
            cu = cap_uv
        elif rect:
            cu = lambda p, k=k: ((rect[0] + rect[2]) / 2 / TEX, (rect[1] + (rect[3] - rect[1]) * cum[k] / total) / TEX)
        else:
            cu = lambda p: uv(p, unit(out))
        g = (gid, "cap", end)
        c = mesh.vert(cents[k], cu(cents[k]), g)
        vs = [mesh.vert(p, cu(p), g) for p in ring]
        for j in range(n):
            mesh.tri_out(c, vs[j], vs[(j + 1) % n], out)


def box8_y(y, cx, cz, hx, hz):
    """A small rounded slab ring at height y (8 points)."""
    return ring_y(y, cx, cz, hx, hz, 8, 6.0)


def tex_planar(rect, fn):
    """uv(p, n) for a planar map: fn(p) -> (a, t) in 0..1 across the rect."""
    x0, y0, x1, y1 = rect

    def uv(p, n=None):
        a, t = fn(p)
        return ((x0 + (x1 - x0) * clamp(a)) / TEX, (y0 + (y1 - y0) * clamp(t)) / TEX)
    return uv


# ================================================================= SHIV
# Axis Y. A long rag-taped handle with a lumpy pommel (y -12.4 .. 4.4, so the hand holds tape wherever it is: the vanilla
# bat's handle is at y -9 .. -3, its origin at y 0), a short crude cross-guard of bent steel, then a leaf blade to y 15.3
# (visible blade about 11 = 43% of the bat's 25.9; 12.1 with the hidden root). The blade lies in the XY plane (spine on
# -X, serrated edge on +X), thickness along Z; the guard runs along Z so the shiv is as deep as the bat is (5.3 vs 5.7).
SV_BLADE = (1, 1, 57, 125)   # planar map of the blade: x -2.8 .. 2.8, y 15.3 .. 3.0
SV_TAPE = (60, 1, 127, 62)   # ring map round the handle: u round, v from the butt up
SV_GUARD = (60, 66, 127, 125)  # the cross-guard (bent steel)
SV_BX0, SV_BX1, SV_BY0, SV_BY1 = -2.8, 2.8, 3.0, 15.3
SV_BUTT, SV_COLLAR_TOP = -12.4, 4.4
SV_SHIFT = 0.8  # the blade is centred on the handle axis


def blade_stations():
    """(y, x_spine, x_edge, thickness): the serrated edge is a run of rip-saw teeth, the spine a plain line that hooks in
    to the clip point. Shared by the geometry and the paint (edge line, blood)."""
    st = [(3.2, -1.2, 1.9, 1.4), (4.7, -1.5, 2.3, 1.5), (5.5, -1.9, 2.8, 1.5)]
    y0 = 5.5
    for i in range(5):  # five teeth: a long ramp out, then a sharp drop back
        base = lambda y: 2.7 - (y - 5.5) * 0.08
        a, b = y0 + 1.30 * i, y0 + 1.30 * i + 1.05
        st.append((a, -1.9 + 0.03 * i, base(a) - 0.15, 1.5 - 0.04 * i))
        st.append((b, -1.87 + 0.03 * i, base(b) + 1.0, 1.5 - 0.04 * i))
    st += [(12.0, -1.8, 2.1, 1.25), (12.9, -1.55, 1.9, 1.1), (13.8, -1.0, 1.5, 0.85), (14.6, -0.1, 1.0, 0.5),
           (15.3, 0.85, 0.85, 0.0)]
    return [(y, xs - SV_SHIFT, xe - SV_SHIFT, t) for y, xs, xe, t in st]


def blade_rings():
    rings = []
    for y, xs, xe, t in blade_stations():
        xm = xs + 0.40 * (xe - xs)  # the ground bevel is the outer 60 percent of the width
        h = t / 2.0
        rings.append([(xe, y, 0.0), (xm, y, h), (xs, y, h), (xs, y, -h), (xm, y, -h)])
    return rings


def build_shiv():
    mesh = Mesh()
    # --- blade: flat shaded facets, planar texture map (x, y) so the paint can follow the edge line
    uv = tex_planar(SV_BLADE, lambda p: ((p[0] - SV_BX0) / (SV_BX1 - SV_BX0), (SV_BY1 - p[1]) / (SV_BY1 - SV_BY0)))
    loft(mesh, "blade", blade_rings(), uv=uv, caps=(True, False), flat=True)
    # --- handle: a rag knot for a pommel, then a strip wrapped in turns (ridges), a thick collar against the guard
    prof = [(SV_BUTT, 1.0, 0.9), (-12.15, 1.8, 1.65), (-11.4, 2.1, 1.9), (-10.5, 1.95, 1.75), (-9.7, 1.4, 1.3)]
    y = -9.0
    for _ in range(13):  # ridges every 0.9: the turns of tape stand out of the strip
        prof.append((y, 1.42, 1.28))
        prof.append((y + 0.42, 1.62, 1.46))
        y += 0.9
    prof += [(2.85, 1.5, 1.35), (3.15, 1.85, 1.6), (4.1, 1.95, 1.65), (SV_COLLAR_TOP, 1.35, 1.1)]
    rings = [ring_y(yy, 0.0, 0.0, rx, rz, 8, 2.6) for yy, rx, rz in prof]
    loft(mesh, "tape", rings, rect=SV_TAPE, caps=(True, True))
    # --- the crude cross-guard: a bent strip of steel through the collar, along Z
    gu = [(-2.65, 0.55, 0.42), (-2.15, 1.0, 0.75), (-1.5, 1.05, 0.8), (1.5, 1.05, 0.8), (2.15, 1.0, 0.75), (2.65, 0.55, 0.42)]
    loft(mesh, "guard", [ring_z(z, 0.0, 3.55, rx, ry, 8, 3.0) for z, rx, ry in gu], rect=SV_GUARD, caps=(True, True))
    return mesh, paint_shiv()


def paint_shiv():
    steel = Fbm(61, 5, 8, 4)
    grind = Fbm(62, 3, 40, 2)
    pit = Fbm(63, 14, 16, 3)
    rustn = Fbm(64, 7, 9, 4)
    drip = Fbm(65, 20, 4, 2)
    cloth = Fbm(66, 30, 30, 2)
    dirt = Fbm(67, 6, 6, 4)
    st = blade_stations()

    def edge_at(y):
        """x_spine, x_edge at height y (linear between stations)."""
        for k in range(len(st) - 1):
            if st[k][0] <= y <= st[k + 1][0]:
                f = (y - st[k][0]) / ((st[k + 1][0] - st[k][0]) or 1)
                return lerp(st[k][1], st[k + 1][1], f), lerp(st[k][2], st[k + 1][2], f)
        return st[0][1], st[0][2]

    def blade(a, t):
        x = SV_BX0 + a * (SV_BX1 - SV_BX0)
        y = SV_BY1 - t * (SV_BY1 - SV_BY0)
        xs, xe = edge_at(y)
        w = (x - xs) / ((xe - xs) or 1)  # 0 at the spine, 1 at the edge
        n = steel.at(a, t)
        col = mix((112, 124, 114), (206, 218, 204), smooth(0.2, 0.8, n))  # grey-green prison steel
        col = shade(col, 0.80 + 0.38 * grind.at(a, t * 0.5))  # file marks along the length
        col = mix(col, (54, 60, 54), 0.7 * smooth(0.64, 0.76, pit.at(a, t)))  # pitting
        if w < 0.60:  # the flat of the blade: a rust-orange bloom, as in the icon
            r = smooth(0.62, 0.74, rustn.at(a, t))
            col = mix(col, mix((190, 100, 36), (110, 54, 22), pit.at(a, t)), 0.85 * r)
        else:  # the ground bevel: bright, with a hard bright line right at the cutting edge
            col = shade(col, 1.18)
            col = mix(col, (240, 246, 236), 0.9 * smooth(0.9, 0.97, w))
            col = mix(col, (48, 52, 48), smooth(0.58, 0.62, w) * smooth(0.66, 0.62, w))  # dark line where the bevel starts
        col = mix(col, (58, 64, 58), 0.8 * smooth(0.07, 0.0, w))  # darker spine line
        # dried blood: streaks that run down the flat from the point (long drips, clean steel between them), fresh and
        # red at the tip, brown further down; the bevel stays mostly clean so the edge still shines
        streak = smooth(0.42, 0.62, drip.at(a, t))
        reach = smooth(8.5, 14.6, y)  # how far down the blade the blood runs
        b = streak * reach * 1.15 + smooth(14.0, 15.3, y) * 0.55
        b *= 0.55 + 0.45 * smooth(0.95, 0.45, w)  # thinner toward the edge
        b = clamp(b * (0.75 + 0.5 * dirt.at(a, t)))
        fresh = smooth(11.5, 15.0, y)
        bc = mix((92, 20, 14), (186, 20, 16), fresh * (0.5 + 0.7 * dirt.at(a, t * 2)))
        return mix(col, bc, 0.92 * smooth(0.25, 0.6, b))

    def tape(a, t):  # t = 0 at the butt; wraps run round the handle
        y = SV_BUTT + t * (SV_COLLAR_TOP - SV_BUTT)
        col = mix((176, 168, 138), (118, 110, 86), cloth.at(a, t))
        if y > -9.4:
            ph = ((y + 9.0) / 0.9) % 1.0
            col = shade(col, 0.66 + 0.46 * smooth(0.0, 0.3, ph) * smooth(1.0, 0.7, ph))
            if ph < 0.09:  # dark gap between two turns
                col = (22, 19, 14)
        else:  # the rag knot at the butt: dirty and dark, crossed with strips
            cross_ = smooth(0.4, 0.6, abs(((a * 3 + t * 2) % 1.0) - 0.5) * 2)
            col = shade(mix(col, (96, 84, 62), 0.5), 0.75 + 0.35 * cross_)
        col = mix(col, (60, 48, 36), 0.7 * smooth(0.55, 0.8, dirt.at(a, t)))  # grime
        col = mix(col, (150, 16, 12), 0.7 * smooth(0.78, 0.86, drip.at(a * 0.4, t)))  # stains
        if y > 3.1:  # the thick collar at the blade is dark with old blood
            col = mix(col, (70, 18, 14), smooth(3.1, 3.7, y) * 0.8)
        return col

    def guard(a, t):  # bent steel: dark with rust, bright worn ends
        col = mix((70, 74, 70), (150, 156, 148), steel.at(a, t))
        col = mix(col, (190, 100, 36), 0.8 * smooth(0.62, 0.74, rustn.at(a, t)))
        col = mix(col, (230, 236, 226), 0.8 * smooth(0.12, 0.0, min(t, 1 - t)))
        return col

    tex = Texture((40.0, 40.0, 38.0), gain=1.25, sat=1.1)
    tex.region(SV_BLADE, blade, wrap=False)
    tex.region(SV_TAPE, tape)
    tex.region(SV_GUARD, guard)
    return tex.render()


# ================================================================= GAUNTLET
# Axis Y from the cuff (-Y, the forearm) to the knuckles (+Y), back of the hand toward +Z, centred on the origin. 35% of
# the bat's length (9.06), about 6.6 wide: a clenched fist in a charred brown leather gauntlet, four brass-orange spikes on
# the knuckles, an iron bar across the fingers, a flared cuff with two riveted iron straps.
GA_LEATHER = (1, 1, 64, 126)
GA_BRASS = (67, 1, 127, 40)
GA_IRON = (67, 43, 127, 70)
GA_PLATE = (67, 73, 127, 100)  # the back plate, planar x / y
GA_SPIKE = (67, 103, 127, 127)
GA_FX = (-2.25, -0.75, 0.75, 2.25)


def build_gauntlet():
    mesh = Mesh()
    # cuff, flared at the mouth
    cuff = [(-4.53, 2.45, 2.0), (-4.30, 2.85, 2.35), (-3.40, 2.70, 2.25), (-2.2, 2.65, 2.25), (-1.45, 2.85, 2.40)]
    loft(mesh, "cuff", [ring_y(y, 0.0, -0.1, rx, rz, 14, 3.0) for y, rx, rz in cuff], rect=GA_LEATHER, caps=(True, True))
    # two iron straps with rivets painted on
    for k, (y0, y1) in enumerate(((-4.0, -3.55), (-2.75, -2.3))):
        rx0 = 2.72 if k == 0 else 2.66
        rings = []
        for y, d in ((y0, 0.02), (y0 + 0.07, 0.16), (y1 - 0.07, 0.16), (y1, 0.02)):
            rings.append(ring_y(y, 0.0, -0.1, rx0 + d, (rx0 - 0.4) + d, 14, 3.0))
        loft(mesh, ("strap", k), rings, rect=GA_IRON)
    # the fist: back of the hand, then the knuckle line
    hand = [(-1.7, 2.8, 2.35, -0.1), (-0.5, 3.05, 2.55, 0.0), (1.1, 3.2, 2.6, 0.1), (2.6, 3.2, 2.45, 0.2),
            (3.4, 3.0, 2.1, 0.2), (3.75, 2.55, 1.7, 0.2), (3.98, 1.7, 1.1, 0.2)]
    def hand_cap(p):  # planar over the top of the fist, into the lower part of the leather rect
        return ((GA_LEATHER[0] + (GA_LEATHER[2] - GA_LEATHER[0]) * (0.5 + p[0] / 7.0)) / TEX,
                (GA_LEATHER[1] + (GA_LEATHER[3] - GA_LEATHER[1]) * (0.5 + p[2] / 9.0)) / TEX)
    loft(mesh, "hand", [ring_y(y, 0.0, cz, rx, rz, 14, 3.2) for y, rx, rz, cz in hand], rect=GA_LEATHER, cap_uv=hand_cap)
    # four finger lumps standing out of the back of the fist
    for i, xc in enumerate(GA_FX):
        fing = [(0.1, 0.80, 0.55), (1.0, 0.86, 0.85), (2.5, 0.88, 0.95), (3.4, 0.72, 0.80), (3.95, 0.34, 0.38)]
        loft(mesh, ("finger", i), [ring_y(y, xc, 2.2, rx, rz, 10, 2.4) for y, rx, rz in fing], rect=GA_LEATHER, caps=(True, True))
    # the thumb, clamped across the fingers under the bar
    th = [(3.05, 0.8, 0.75), (2.2, 0.86, 0.8), (1.0, 0.78, 0.7), (0.0, 0.6, 0.55), (-0.55, 0.28, 0.3)]
    loft(mesh, "thumb", [ring_x(x, 0.95, 3.0, ry, rz, 10, 2.4) for x, ry, rz in th], rect=GA_LEATHER)
    # a riveted iron plate bolted on the back of the hand
    pl = [(-1.75, 1.5), (-1.55, 1.9), (-0.35, 2.0), (-0.1, 1.7)]
    pu = tex_planar(GA_PLATE, lambda p: ((p[0] + 2.1) / 4.2, (0.5 - p[1]) / 2.0 + 0.5 if False else (1.0 - (p[1] + 1.8) / 2.0)))
    loft(mesh, "plate", [box8_y(y, 0.0, 2.58, hx, 0.3) for y, hx in pl], uv=pu, flat=True)
    # iron bar (the brass knuckle plate) across the backs of the fingers
    bar = [(2.0, 3.05, 0.28), (2.15, 3.2, 0.5), (2.9, 3.2, 0.5), (3.05, 3.05, 0.28)]
    loft(mesh, "bar", [ring_y(y, 0.0, 3.0, rx, rz, 14, 3.0) for y, rx, rz in bar], rect=GA_BRASS)
    # knuckle spikes
    for i, xc in enumerate(GA_FX):
        tube(mesh, ("spike", i), [(xc, 3.25, 2.25), (xc, 3.85, 2.4), (xc, 4.53, 2.6)], [0.66, 0.52, 0.0], (1.0, 0.0, 0.0), 6, GA_SPIKE)
    mesh.pos = [(x, y, z - 0.615) for x, y, z in mesh.pos]  # centre the depth on the origin (thumb and bar stick out at +Z)
    return mesh, paint_gauntlet()


def paint_gauntlet():
    hide = Fbm(71, 14, 6, 3, 0.4)
    scorch = Fbm(72, 6, 3, 3, 0.5)
    crack = Fbm(73, 20, 8, 2)
    grit = Fbm(74, 70, 30, 2)
    metal = Fbm(75, 7, 7, 4)
    soot = Fbm(76, 6, 6, 4)

    def leather(a, t):
        n = hide.at(a, t)
        col = mix((96, 58, 44), (150, 98, 74), smooth(0.3, 0.7, n))
        col = shade(col, 0.88 + 0.24 * grit.at(a, t))
        cr = abs(crack.at(a * 0.7, t * 1.3) - 0.5) * 2.0  # creases: dark thin lines where the leather folds
        col = mix(col, (28, 16, 10), 0.85 * smooth(0.06, 0.0, cr))
        col = mix(col, (52, 36, 30), 0.8 * smooth(0.64, 0.74, scorch.at(a, t)))  # charred, but not black: the form stays readable
        hot = smooth(0.09, 0.0, cr) * smooth(0.42, 0.55, scorch.at(a, t))  # embers glow in the creases of the char
        col = mix(col, (255, 150, 34), 0.95 * hot)
        st = smooth(0.012, 0.0, abs(t - 0.5)) * (1.0 if int(a * 44) % 2 == 0 else 0.0)  # stitching
        return mix(col, (222, 200, 150), 0.6 * st)

    def brass(a, t):
        n = metal.at(a, t)
        col = mix((120, 70, 22), (255, 170, 52), smooth(0.2, 0.9, n))
        col = shade(col, 0.8 + 0.4 * (1 - abs(t - 0.5) * 2))
        return mix(col, (60, 30, 12), 0.7 * smooth(0.7, 0.8, soot.at(a, t)))

    def iron(a, t):  # a strap: dark iron, brass rivets in a row
        col = mix((34, 32, 32), (96, 92, 88), metal.at(a, t))
        col = mix(col, (205, 200, 190), 0.8 * smooth(0.12, 0.0, min(t, 1 - t)))  # bright edges
        rv = abs(((a * 14) % 1.0) - 0.5)
        if abs(t - 0.5) < 0.2 and rv < 0.18:
            col = mix(col, (255, 176, 60), 0.95 * smooth(0.18, 0.1, rv))
        return col

    def plate(a, t):  # dark scarred iron with four brass rivets and a bright rim
        col = mix((40, 40, 44), (112, 110, 112), metal.at(a, t))
        col = mix(col, (28, 24, 22), 0.6 * smooth(0.55, 0.75, soot.at(a, t)))
        col = mix(col, (210, 206, 196), 0.85 * smooth(0.10, 0.0, min(a, 1 - a, t, 1 - t)))
        for ra, rt in ((0.2, 0.18), (0.8, 0.18), (0.2, 0.82), (0.8, 0.82)):
            col = mix(col, (255, 180, 64), 0.95 * smooth(0.1, 0.06, math.hypot((a - ra) * 4.2 / 2.0, (t - rt))))
        return col

    def spike(a, t):  # t = 0 at the tip: bright hot point, brass behind, dark at the base
        col = mix((255, 236, 170), (214, 120, 34), smooth(0.05, 0.4, t))
        col = mix(col, (74, 38, 16), smooth(0.55, 1.0, t))
        return shade(col, 0.74 + 0.4 * abs(math.sin(a * math.pi)))

    tex = Texture((60.0, 38.0, 24.0), gain=1.25, sat=1.15)
    tex.region(GA_LEATHER, leather)
    tex.region(GA_BRASS, brass)
    tex.region(GA_IRON, iron)
    tex.region(GA_PLATE, plate, wrap=False)
    tex.region(GA_SPIKE, spike)
    return tex.render()


# ================================================================= RAILSPIKE
# Same box and origin as TailNail: a handle along Y from the butt (y -4.3), a head along Z, and on top a plank with a big
# rust-orange railway spike driven through it, point up. Unlike the vanilla mallet the head is a cross-peen sledge: a
# flared square striking face at +Z, a tapering chisel peen at -Z (the silhouette is lopsided, not a barrel).
RS_HANDLE = (1, 1, 40, 127)
RS_HEAD = (43, 1, 127, 52)
RS_HCAP = (43, 55, 95, 107)
RS_PLANK = (98, 55, 127, 90)
RS_SPIKE = (98, 93, 127, 127)
RS_HEAD_Y = 9.6  # head centre height
RS_Z0, RS_Z1 = -9.0, 8.4  # the peen tip .. the striking face
RS_PLANK_Z = (-3.6, 6.2)
RS_PLANK_Y = (13.0, 14.2)
RS_SPIKE_AT = (0.0, 1.3)  # x, z of the spike on the plank


def ring_plane(c, u, v, a, b):
    """A 4-point ring: centre c, half-sizes a along u and b along v (u and v unit vectors)."""
    return [add(c, add(mul(u, sa * a), mul(v, sb * b))) for sa, sb in ((1, 1), (-1, 1), (-1, -1), (1, -1))]


def shard(mesh, gid, base, tilt, ang, ln, w, th):
    """A wooden splinter standing out of the plank: a flat tapered blade of length ln leaning out by `tilt` radians
    from vertical toward direction `ang` (radians, in the XZ plane)."""
    d = unit((math.sin(tilt) * math.cos(ang), math.cos(tilt), math.sin(tilt) * math.sin(ang)))
    u = unit(cross(d, (0.0, 1.0, 0.0)) if abs(d[1]) < 0.99 else (1.0, 0.0, 0.0))
    v = unit(cross(u, d))
    rings = [ring_plane(add(base, mul(d, ln * f)), u, v, w * k, th * k) for f, k in ((0.0, 1.0), (0.45, 0.8), (1.0, 0.07))]
    loft(mesh, gid, rings, rect=RS_PLANK, flat=True)


def build_railspike():
    mesh = Mesh()
    # handle: flared knob at the butt, a rag wrap round the grip, a slight swell up to the head
    hp = [(-4.30, 1.55, 1.30), (-4.10, 2.05, 1.70), (-3.20, 1.95, 1.62), (-2.60, 1.45, 1.20), (-1.0, 1.50, 1.22),
          (2.5, 1.60, 1.32), (6.0, 1.72, 1.45), (9.5, 1.85, 1.55)]
    loft(mesh, "handle", [ring_y(y, 0.0, 0.0, rx, rz, 10, 2.4) for y, rx, rz in hp], rect=RS_HANDLE, caps=(True, True))
    # cross-peen sledge head: chisel peen at -Z, waist round the eye, flared striking face at +Z
    prof = [(RS_Z0, 3.7, 0.55), (-8.3, 4.1, 1.0), (-6.2, 4.7, 2.0), (-3.8, 5.15, 3.0), (-1.4, 5.5, 3.5), (1.5, 5.45, 3.6),
            (4.5, 5.3, 3.55), (6.6, 5.35, 3.55), (7.0, 6.0, 4.35), (7.9, 6.0, 4.35), (RS_Z1, 5.2, 3.7)]

    def hcap(p):
        return ((RS_HCAP[0] + (RS_HCAP[2] - RS_HCAP[0]) * (0.5 + p[0] / 12.6)) / TEX,
                (RS_HCAP[1] + (RS_HCAP[3] - RS_HCAP[1]) * (0.5 - (p[1] - RS_HEAD_Y) / 9.0)) / TEX)
    loft(mesh, "head", [ring_z(z, 0.0, RS_HEAD_Y, rx, ry, 12, 4.0) for z, rx, ry in prof], rect=RS_HEAD, cap_uv=hcap)
    # plank on top of the head: wood board with chamfered corners, grain running along Z
    (z0, z1), (y0, y1) = RS_PLANK_Z, RS_PLANK_Y
    plank = [ring_z(z, 0.0, (y0 + y1) / 2, 4.1, (y1 - y0) / 2, 8, 6.0) for z in (z0, z1)]
    pu = tex_planar(RS_PLANK, lambda p: ((p[2] - z0) / (z1 - z0), (p[0] + 4.1) / 8.2 if abs(p[1] - 13.6) > 0.3 else 0.5))
    loft(mesh, "plank", plank, uv=pu, flat=True)
    # four nails hammered into the corners of the plank
    for k, (nx, nz) in enumerate(((3.0, 5.0), (-3.0, 5.1), (-3.0, -2.4), (3.1, -2.3))):
        r0 = 0.9 - 0.08 * (k % 2)
        loft(mesh, ("nail", k), [ring_y(y, nx, nz, r, r, 6, 2.0) for y, r in ((14.1, 0.4), (14.28, r0), (14.62, r0), (14.85, 0.35))],
             rect=RS_SPIKE)
    # the spike: square shank with two saw-tooth barbs, a crushed foot where it meets the plank, a chisel point
    sx, sz = RS_SPIKE_AT
    st = [(13.8, 1.95, 1.95), (14.5, 1.95, 1.95), (14.95, 1.5, 1.5), (16.9, 1.5, 1.5), (17.5, 1.8, 1.5), (17.6, 1.45, 1.5),
          (19.1, 1.4, 1.45), (19.7, 1.7, 1.4), (19.8, 1.3, 1.4), (21.0, 0.8, 1.0), (22.4, 0.14, 0.4), (22.8, 0.0, 0.0)]
    rings = []
    for y, hx, hz in st:
        rings.append([(sx + hx, y, sz + hz), (sx - hx, y, sz + hz), (sx - hx, y, sz - hz), (sx + hx, y, sz - hz)])
    loft(mesh, "spike", rings, rect=RS_SPIKE, caps=(True, False), flat=True)
    # splinters torn up round the spike
    for k, (ang, tilt, ln, w) in enumerate(((20, 0.55, 2.8, 0.55), (85, 0.8, 2.0, 0.5), (150, 0.5, 3.1, 0.6),
                                            (215, 0.75, 2.2, 0.5), (275, 0.6, 2.9, 0.55), (335, 0.85, 1.8, 0.45))):
        a = math.radians(ang)
        base = (sx + 2.35 * math.cos(a), 14.0, sz + 2.35 * math.sin(a))
        shard(mesh, ("shard", k), base, tilt, a, ln, w * 1.5, 0.3)
    return mesh, paint_railspike()


def paint_railspike():
    wood = Fbm(81, 6, 40, 3)
    fine = Fbm(82, 40, 40, 2)
    steel = Fbm(83, 8, 6, 4)
    rustn = Fbm(84, 7, 9, 4)
    pitn = Fbm(85, 16, 16, 3)
    cloth = Fbm(86, 26, 26, 2)
    grain = Fbm(87, 4, 44, 3)

    def handle(a, t):  # t = 0 at the butt knob
        y = -4.3 + t * 13.8
        col = mix((46, 30, 22), (112, 78, 52), smooth(0.3, 0.7, wood.at(a, t)))
        col = shade(col, 0.8 + 0.4 * fine.at(a, t))
        if -3.0 < y < 0.8:  # filthy rag wrap on the grip
            ph = (y * 2.0 + a * 0.4) % 1.0
            rag = mix((170, 160, 128), (120, 110, 84), cloth.at(a, t))
            rag = shade(rag, 0.66 + 0.4 * smooth(0.0, 0.3, ph) * smooth(1.0, 0.7, ph))
            if ph < 0.09:
                rag = (22, 18, 14)
            col = mix(col, rag, smooth(-3.0, -2.8, y) * smooth(0.8, 0.6, y))
        if y < -3.0:
            col = mix(col, (24, 18, 14), 0.55)
        return col

    def head(a, t):  # a steel sledge: dark gunmetal body, bright chamfers at the face and the peen edge, a rust bloom
        z = RS_Z0 + t * (RS_Z1 - RS_Z0)
        n = steel.at(a, t)
        col = mix((70, 78, 88), (150, 162, 176), smooth(0.2, 0.85, n))
        col = shade(col, 0.82 + 0.36 * fine.at(a, t))
        col = mix(col, (190, 100, 36), 0.7 * smooth(0.66, 0.76, rustn.at(a, t)))
        col = mix(col, (230, 238, 246), 0.9 * smooth(0.55, 0.0, abs(z - 7.4)))  # the flared lip of the face
        col = mix(col, (230, 238, 246), 0.9 * smooth(1.2, 0.0, z - RS_Z0))  # the chisel edge of the peen
        col = mix(col, (28, 30, 36), 0.6 * smooth(4.0, 2.6, abs(z - 0.5)))  # dark waist round the eye
        return col

    def hcap(a, t):  # the striking face: bright, battered, a dark rim
        x, y = (a - 0.5) * 12.6, (0.5 - t) * 9.0
        r = math.hypot(x / 5.4, y / 3.9)
        col = mix((190, 198, 208), (110, 120, 132), smooth(0.2, 1.0, fine.at(a, t)))
        col = mix(col, (240, 246, 250), 0.8 * smooth(0.55, 0.0, r))
        col = mix(col, (60, 62, 68), 0.9 * smooth(0.85, 1.05, r))
        col = mix(col, (190, 96, 34), 0.8 * smooth(0.72, 0.8, rustn.at(a, t)) * smooth(0.5, 0.9, r))
        return col

    def plank(a, t):  # pale board, dark grain, a couple of dark knots
        g = grain.at(a, t)
        col = mix((206, 166, 108), (136, 98, 58), smooth(0.35, 0.75, g))
        col = shade(col, 0.84 + 0.3 * fine.at(a, t))
        for ka, kt in ((0.28, 0.5), (0.74, 0.3)):
            d = math.hypot((a - ka) * 6.0, (t - kt) * 4.0)
            col = mix(col, (44, 26, 14), 0.9 * smooth(0.9, 0.4, d))
        return mix(col, (232, 204, 150), 0.6 * smooth(0.8, 1.0, a))  # pale fresh wood toward the splinters

    def spike(a, t):  # t = 0 at the base: rust-orange, dark pits, a bright worn tip
        n = rustn.at(a, t)
        col = mix((206, 92, 26), (255, 140, 44), smooth(0.2, 0.9, n))
        col = mix(col, (112, 44, 16), 0.85 * smooth(0.62, 0.74, pitn.at(a, t)))
        col = mix(col, (60, 26, 12), 0.75 * smooth(0.3, 0.0, t))
        col = mix(col, (255, 214, 130), 0.85 * smooth(0.78, 0.97, t))  # polished point
        edge = abs(((a * 4.0) % 1.0) - 0.5) * 2.0  # a dark crease on each corner
        return mix(col, (50, 22, 10), 0.7 * smooth(0.82, 1.0, edge))

    tex = Texture((50.0, 38.0, 30.0), gain=1.22, sat=1.15)
    tex.region(RS_HANDLE, handle)
    tex.region(RS_HEAD, head)
    tex.region(RS_HCAP, hcap, wrap=False)
    tex.region(RS_PLANK, plank, wrap=False)
    tex.region(RS_SPIKE, spike)
    return tex.render()


# ================================================================= registry, generator, validator
MODELS = [
    ("shiv", build_shiv, "BaseballBat"),
    ("gauntlet", build_gauntlet, "BaseballBat"),
    ("railspike", build_railspike, "TailNail"),
]


def validate_held(stem, gltf, binary, png):
    """make_meshes' strict validator (accessors, normals, winding, no duplicate directed edges, one primitive ...) with
    the reference box and the triangle limits of this group, restored afterwards."""
    saved = (dict(mm.VANILLA), mm.TOL, mm.TRI_MIN, mm.TRI_MAX)
    mm.VANILLA[stem] = REF[stem]
    mm.TOL, mm.TRI_MIN, mm.TRI_MAX = TOL, TRI_MIN, TRI_MAX
    try:
        return mm.validate(stem, gltf, binary, png)
    finally:
        mm.VANILLA.clear()
        mm.VANILLA.update(saved[0])
        mm.TOL, mm.TRI_MIN, mm.TRI_MAX = saved[1:]


def generate(only=None):
    files, stats = {}, {}
    for slug, build, _ref in MODELS:
        if only and slug not in only:
            continue
        mesh, tex = build()
        gltf, binary = mm.build_gltf(slug, slug.title(), mesh)
        png = tex.png()
        stats[slug] = validate_held(slug, gltf, binary, png)
        files[slug + ".gltf"], files[slug + ".bin"], files[slug + ".png"] = gltf, binary, png
    return files, stats


def deviations(slug, stat):
    _, rmin, rmax, _ = REF[slug]
    out = []
    for k in range(3):
        size, rsize = stat["max"][k] - stat["min"][k], rmax[k] - rmin[k]
        mid, rmid = (stat["max"][k] + stat["min"][k]) / 2, (rmax[k] + rmin[k]) / 2
        out.append((100.0 * (size - rsize) / rsize, mid - rmid))
    return out


def main():
    check = "--check" in sys.argv
    files, stats = generate()
    if check:
        bad = [n for n, d in files.items() if not (OUT / n).is_file() or (OUT / n).read_bytes() != d]
        print("held meshes up to date" if not bad else "held meshes out of date: " + ", ".join(bad))
        sys.exit(1 if bad else 0)
    OUT.mkdir(parents=True, exist_ok=True)
    for n, d in files.items():
        (OUT / n).write_bytes(d)
    for slug, s in stats.items():
        dv = deviations(slug, s)
        print(f"{slug}: {s['vertices']} verts, {s['triangles']} tris, box {[round(v, 3) for v in s['min']]} .. "
              f"{[round(v, 3) for v in s['max']]} vs {s['ref']}; size dev % "
              + " ".join(f"{a}{d[0]:+.1f}" for a, d in zip("xyz", dv)) + "; centre off "
              + " ".join(f"{a}{d[1]:+.2f}" for a, d in zip("xyz", dv)))


if __name__ == "__main__":
    main()
