// Generates mod/postfx/guts/effect.ini and guts.frag from guts.frag.in: the four slots of sixteen chain points are
// separate vec4 uniforms (a Melange parameter holds at most four floats), so the declarations, the effect.ini sections and
// the copy-out of the chosen slot are written out here instead of by hand.
//
//   node tools/gen_guts.js            (from plugins/bloodsand)
const fs = require('fs');
const path = require('path');

const SLOTS = 4;
const POINTS = 16;
const root = path.join(__dirname, '..');
const outDir = path.join(root, 'mod', 'postfx', 'guts');
fs.mkdirSync(outDir, { recursive: true });

const names = [];
for (let k = 0; k < SLOTS; k++) {
    for (const h of ['a', 'b', 'c', 'd']) names.push(`g${k}${h}`);
    for (let i = 0; i < POINTS; i++) names.push(`g${k}_${i}`);
}
const decl = [];
for (let k = 0; k < SLOTS; k++) {
    const list = [`p_g${k}a`, `p_g${k}b`, `p_g${k}c`, `p_g${k}d`];
    for (let i = 0; i < POINTS; i++) list.push(`p_g${k}_${i}`);
    decl.push('uniform vec4 ' + list.join(', ') + ';');
}

const load = [];
for (let k = 0; k < SLOTS; k++) {
    const cond = k === 0 ? 'if (sel < 0.5) {' : k < SLOTS - 1 ? `} else if (sel < ${k}.5) {` : '} else {';
    load.push('    ' + cond);
    load.push(`        HB = p_g${k}b; HC = p_g${k}c; HD = p_g${k}d;`);
    for (let i = 0; i < POINTS; i++) load.push(`        PT[${i}] = p_g${k}_${i};`);
}
load.push('    }');

let src = fs.readFileSync(path.join(__dirname, 'guts.frag.in'), 'utf8').replace(/\r\n/g, '\n');
src = src.replace('//@UNIFORMS@', decl.join('\n')).replace('//@LOAD@', load.join('\n'));
fs.writeFileSync(path.join(outDir, 'guts.frag'), src.replace(/\n/g, '\r\n'));

const label = {
    a: 'bounding sphere: centre and radius',
    b: 'body centre and wetness',
    c: 'ground plane: normal and offset',
    d: 'seed and freshness',
};
const ini = [];
ini.push('; Intestines, ray-marched as smooth-unioned tubes along a chain of 16 points per gutted worm, for up to four worms at once.');
ini.push('; Bloodsand\'s Lua simulates the chain and sends it every frame with wum.postfx.setTransient, so every parameter but the');
ini.push('; colour and the opacity is hidden. Each slot has a header (gka..gkd) and its 16 points gk_0..gk_15 (x, y, z, tube radius).');
ini.push('; This file and guts.frag are generated by tools/gen_guts.js from tools/guts.frag.in.');
ini.push('[effect]');
ini.push('title=Bloodsand guts');
ini.push('stage=PostWorld');
ini.push('order=52');
ini.push('enabled=0');
ini.push('');
for (const n of names) {
    const m = /^g(\d)(?:([abcd])|_(\d+))$/.exec(n);
    const lab = m[2] ? `Gut ${m[1]} ${label[m[2]]} (set by Bloodsand)` : `Gut ${m[1]} point ${m[3]} (set by Bloodsand)`;
    ini.push(`[param.${n}]`);
    ini.push('type=color');
    ini.push('default=0,0,0,0');
    ini.push(`label=${lab}`);
    ini.push('hidden=1');
    ini.push('');
}
ini.push('[param.blood]');
ini.push('type=color');
ini.push('default=0.42,0.02,0.02');
ini.push('label=Blood colour');
ini.push('');
ini.push('[param.strength]');
ini.push('type=float');
ini.push('default=1');
ini.push('min=0');
ini.push('max=1');
ini.push('label=Opacity');
ini.push('');
ini.push('[pass.guts]');
ini.push('shader=guts.frag');
ini.push('inputs=scene,depth');
ini.push('');
fs.writeFileSync(path.join(outDir, 'effect.ini'), ini.join('\r\n'));
console.log('wrote', outDir, names.length, 'params');
