// Generates mod/postfx/gibs/effect.ini and gibs.frag from gibs.frag.in: the 16 slots of four vec4 are separate uniforms (a
// Melange parameter holds at most four floats), so the declarations, the effect.ini sections, the copy-out of the chosen slot
// and the sphere tests are written out here instead of by hand.
//
//   node tools/gen_gibs.js            (from plugins/bloodsand)
const fs = require('fs');
const path = require('path');

const SLOTS = 16;
const root = path.join(__dirname, '..');
const outDir = path.join(root, 'mod', 'postfx', 'gibs');
fs.mkdirSync(outDir, { recursive: true });

const heads = ['a', 'b', 'c', 'd'];
const decl = [];
for (let row = 0; row < SLOTS; row += 4) {
    const list = [];
    for (let k = row; k < row + 4; k++) for (const h of heads) list.push(`p_g${k}${h}`);
    decl.push('uniform vec4 ' + list.join(', ') + ';');
}

const load = [];
for (let k = 0; k < SLOTS; k++) {
    const cond = k === 0 ? 'if (sel < 0.5) {' : k < SLOTS - 1 ? `} else if (sel < ${k}.5) {` : '} else {';
    load.push('    ' + cond);
    load.push(`        A = p_g${k}a; B = p_g${k}b; GH = p_g${k}c; GD = p_g${k}d;`);
}
load.push('    }');

const bounds = [];
for (let k = 0; k < SLOTS; k++) {
    bounds.push(`    if (p_count > ${k}.5) Bound(p_g${k}a, ${k}.0, camW, dirW, sph0, sph1, sph2);`);
}

let src = fs.readFileSync(path.join(__dirname, 'gibs.frag.in'), 'utf8').replace(/\r\n/g, '\n');
src = src.replace('//@UNIFORMS@', decl.join('\n')).replace('//@LOAD@', load.join('\n')).replace('//@BOUNDS@', bounds.join('\n'));
fs.writeFileSync(path.join(outDir, 'gibs.frag'), src.replace(/\n/g, '\r\n'));

const label = {
    a: 'bounding sphere: centre and radius',
    b: 'orientation (quaternion)',
    c: 'half extents and type',
    d: 'seed, birth, wetness and bloodiness',
};
const ini = [];
ini.push('; Gibs (meat chunks, bone shards and organs), ray-marched as signed distance fields, for up to 16 at once. Bloodsand\'s Lua');
ini.push('; throws them, simulates them (flight, bounces, rolling, rest) and sends each one every frame it moves with');
ini.push('; wum.postfx.setTransient, so every parameter but the colour, the opacity and the drying time is hidden. Each slot gk has');
ini.push('; four vec4: gka bounding sphere, gkb orientation, gkc half extents and type, gkd seed, birth, wetness and bloodiness.');
ini.push('; This file and gibs.frag are generated by tools/gen_gibs.js from tools/gibs.frag.in.');
ini.push('[effect]');
ini.push('title=Bloodsand gibs');
ini.push('stage=PostWorld');
ini.push('order=53');
ini.push('enabled=0');
ini.push('');
for (let k = 0; k < SLOTS; k++) {
    for (const h of heads) {
        ini.push(`[param.g${k}${h}]`);
        ini.push('type=color');
        ini.push('default=0,0,0,0');
        ini.push(`label=Gib ${k} ${label[h]} (set by Bloodsand)`);
        ini.push('hidden=1');
        ini.push('');
    }
}
ini.push('[param.count]');
ini.push('type=float');
ini.push('default=0');
ini.push('label=Highest slot in use plus one (set by Bloodsand)');
ini.push('hidden=1');
ini.push('');
ini.push('[param.clock]');
ini.push('type=float');
ini.push('default=0');
ini.push('label=Clock (set by Bloodsand)');
ini.push('hidden=1');
ini.push('');
ini.push('[param.blood]');
ini.push('type=color');
ini.push('default=0.42,0.02,0.02');
ini.push('label=Blood colour');
ini.push('');
ini.push('[param.strength]');
ini.push('type=float');
ini.push('default=1');
ini.push('min=0');
ini.push('max=1');
ini.push('label=Opacity');
ini.push('');
ini.push('[param.dryTime]');
ini.push('type=float');
ini.push('default=60');
ini.push('min=5');
ini.push('max=300');
ini.push('label=Drying time (seconds)');
ini.push('');
ini.push('[pass.gibs]');
ini.push('shader=gibs.frag');
ini.push('inputs=scene,depth');
ini.push('');
fs.writeFileSync(path.join(outDir, 'effect.ini'), ini.join('\r\n'));
console.log('wrote', path.join(outDir, 'gibs.frag'), 'and effect.ini');
